version: "2"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - misspell

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
