version: 2

project_name: repokeeper

builds:
  - id: repokeeper
    main: .
    binary: repokeeper
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/skaphos/repokeeper/cmd/repokeeper.Version={{.Version}}
      - -X github.com/skaphos/repokeeper/cmd/repokeeper.Commit={{.Commit}}
      - -X github.com/skaphos/repokeeper/cmd/repokeeper.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

homebrew_casks:
  - repository:
      owner: skaphos
      name: homebrew-tools
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/skaphos/repokeeper"
    description: "Track and manage many Git repositories from a single config"
    license: "MIT"
    binaries:
      - repokeeper

snapshot:
  version_template: "{{ .Tag }}-next"
